openapi: 3.0.0
info:
  title: EdgePlayer API
  description: API Doc for edgeplayer-api.
  version: 0.1.1
servers:
  - url: http://localhost:3000/
    description: for development purpose
  - url: https://edgeplayer-api-poc.azurewebsites.net
    description: Production env
components:
  securitySchemes:
    authToken:
      type: apiKey
      in: header  
      name: authorization
  responses:
    UnauthorizedError:
      description: API key is missing or invalid
      headers:
        WWW_Authenticate:
          schema:
            type: string
paths:
# User routes 
# SignUp API
  /api/register:
    post:
      tags:
      - Register
      summary: register a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - firstName
                - lastName
                - companyName
                - password
              properties:
                email:
                  type: string
                  example: "email"
                firstName:
                  type: string
                  example: "firstName"
                lastName:
                  type: string
                  example: "lastName"
                companyName:
                  type: string
                  example: "companyName"
                password:
                  type: string
                  example: "password"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                    description: The user ID.
                  email:
                    type: string
                    description: The user email.

# SignIn API
  /api/signIn:
    post:
      tags:
      - Sign In
      summary: create a session for a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  example: "email"
                password:
                  type: string
                  example: "password"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: The auth token.

#get a user by name
  /api/user:
    get:
      tags:
        - getUser
      security:
        - authToken: []
      parameters:
        - name: Email
          description: user email
          in: query
          required: true
          schema:
            type : string
            example: "testing@yopmail.com"
      description: should return a user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: integer
                    description: The user id.
                  email:
                    type: string
                    description: The user email.
        '401':
          $ref: "#/components/responses/UnauthorizedError"
